### ISSUE TITLE
Setup mon.school website

### ISSUE THREAD

**Issue by anandology** [fossunited/community#44]
## Tasks
- [x] take a new server on Linode/DigitalOcean
- [x] setup frappe-bench in production
- [x] setup nginx and SSL

**Comment by anandology** [comment]
Done.
