### ISSUE TITLE
Fix the design of the home page

### ISSUE THREAD

**Issue by anandology** [fossunited/community#47]
I've setup the home page in the application. It has all the elements, but the design is not in sync with the figma mockup.

Look into that and make it look like the design in figma.

## Tasks

- [ ] Fix the styles of the hero section
- [ ] Fix the styles of the courses section
- [ ] Fix the styles of the recent sketches section
- [ ] Add footer

Leave out the header part for now. 

## Files to look at

* [community/www/home/index.html][1]
* [community/lms/widgets/CourseTeaser.html][2]
* [community/lms/widgets/SketchTeaser.html][3]
 
[1]: https://github.com/fossunited/community/blob/main/community/www/home/index.html
[2]: https://github.com/fossunited/community/blob/main/community/lms/widgets/CourseTeaser.html
[3]: https://github.com/fossunited/community/blob/main/community/lms/widgets/SketchTeaser.html

## Dev Instance

See [README.md][4] for instructions to setup a dev instance.

[4]: https://github.com/fossunited/community#readme

**Comment by khalby786** [comment]
Roger that.

**Comment by khalby786** [comment]
https://github.com/fossunited/community/pull/53

Styles the homepage based on the Figma design, except for the header and footer.

**Comment by anandology** [comment]
done.
