### ISSUE TITLE
Add lesson type video

### ISSUE THREAD

**Issue by anandology** [fossunited/community#57]
Add a new lesson type for showing video.

## Tasks
- [ ] Update the lesson doctype to include fields required for showing video
- [ ] Update the LessonTeaser widget to show appropriate icon
- [ ] Update the lesson template to show video

---

Story #54

**Comment by anandology** [comment]
We are not using lesson types. If there is video, it is just embed into the markdown description.
