### ISSUE TITLE
Add lesson type text

### ISSUE THREAD

**Issue by anandology** [fossunited/community#58]
Add a new lesson type for showing text.

## Tasks
- [ ] Update the lesson doctype to include fields required for showing the text
- [ ] Update the LessonTeaser widget to show appropriate icon
- [ ] Update the lesson template to show the text

---

Story #54

**Comment by anandology** [comment]
We are not using lesson types. All types of lessons are considered as text for now.
