### ISSUE TITLE
Add lesson type quiz

### ISSUE THREAD

**Issue by anandology** [fossunited/community#59]
Add a new lesson type for showing quiz.

The quiz may have an optional hint. The user can submit the answer and the system will tell if the answer is correct.

## Tasks
- [ ] Update the lesson doctype to include fields required for showing quiz
- [ ] Update the LessonTeaser widget to show appropriate icon
- [ ] Update the lesson template to show quiz

---

Story #54

**Comment by anandology** [comment]
we have not added lesson types yet. We'll relook into quiz type later. closing this for now.
