### ISSUE TITLE
Add lesson type practice

### ISSUE THREAD

**Issue by anandology** [fossunited/community#60]
Should this be called practice or exercise?

## Tasks
- [ ] Update the lesson doctype to include fields required for showing practice
- [ ] Update the LessonTeaser widget to show appropriate icon
- [ ] Update the lesson template to show the exercise

## Discussion
It may be a good idea to have multiple exercises clubbed into one lesson.

---

Story #54

**Comment by anandology** [comment]
we have added Exercises instead of lesson type practice.
