### ISSUE TITLE
Checklist for launch

### ISSUE THREAD

**Issue by anandology** [fossunited/community#79]
## mon.school instance

- [ ] setup sending email
- [ ] add about page
- [ ] launching blog post 

## The Joy of Programming Course

- [ ] add joy of programming course
- [ ] add video for the course
- [ ] add course outline
- [ ] create one batch for Navgurukul

## Sketches

- [ ] add 10 sketches
- [ ] 10 sketches from the students of the old batch

**Comment by anandology** [comment]
This issue should be moved to mon_school app.
